<?php


/**
 * Skeleton subclass for representing a row from the 'jobeet_affiliate' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Feb  4 12:52:29 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class JobeetAffiliate extends BaseJobeetAffiliate {

	/**
	 * Initializes internal state of JobeetAffiliate object.
	 * @see        parent::__construct()
	 */
	public function __toString()
  	{
    		return $this->getUrl();
  	}
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // JobeetAffiliate
